version: '3.8'

services: 
  main:
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    container_name: vesti_app
    volumes:
      - .:/app
    ports:
      - ${APP_PORT}:8000
    depends_on: 
      - db

  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: vesti_db
    environment: 
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306